/**
 * TA Voiceover Generator
 * ----------------------
 * Calls ElevenLabs TTS with word-level timestamps, saves the MP3 to
 * public/ and writes synced caption data to src/captions-data.ts.
 *
 * Usage:
 *   1. Add ELEVENLABS_API_KEY=your_key to a .env file in the project root
 *   2. Run: node --env-file=.env --strip-types generate-voiceover.ts
 */

import { writeFileSync, mkdirSync, existsSync } from "fs";

// ── Config ──────────────────────────────────────────────────────────────────

const VOICE_ID = "21m00Tcm4TlvDq8ikWAM"; // Rachel — calm, clear female voice
const FPS = 30;
const SCRIPT =
  "Turn your last trip into a stunning map animation. Watch your route come to life, every stop, every memory.";

const OUTPUT_AUDIO = "public/voiceover.mp3";
const OUTPUT_DATA = "src/captions-data.ts";

// ── Types ────────────────────────────────────────────────────────────────────

type ElevenLabsResponse = {
  audio_base64: string;
  alignment: {
    characters: string[];
    character_start_times_seconds: number[];
    character_end_times_seconds: number[];
  };
};

type CaptionWord = {
  text: string;
  startFrame: number;
  endFrame: number;
};

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Groups character-level alignment data into word-level timing */
function parseWords(alignment: ElevenLabsResponse["alignment"]): CaptionWord[] {
  const { characters, character_start_times_seconds, character_end_times_seconds } =
    alignment;

  const words: CaptionWord[] = [];
  let currentWord = "";
  let wordStartSec = 0;
  let lastCharIdx = -1;

  for (let i = 0; i < characters.length; i++) {
    const char = characters[i];
    const isSeparator = char === " " || char === "." || char === "," || char === "!";

    if (isSeparator) {
      if (currentWord.length > 0) {
        words.push({
          text: currentWord,
          startFrame: Math.round(wordStartSec * FPS),
          endFrame: Math.round(character_end_times_seconds[lastCharIdx] * FPS),
        });
        currentWord = "";
      }
    } else {
      if (currentWord.length === 0) {
        wordStartSec = character_start_times_seconds[i];
      }
      currentWord += char;
      lastCharIdx = i;
    }
  }

  // flush last word
  if (currentWord.length > 0 && lastCharIdx >= 0) {
    words.push({
      text: currentWord,
      startFrame: Math.round(wordStartSec * FPS),
      endFrame: Math.round(character_end_times_seconds[lastCharIdx] * FPS),
    });
  }

  return words;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function generate() {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  if (!apiKey) {
    console.error("❌  ELEVENLABS_API_KEY not found in environment.");
    console.error("    Add it to a .env file and run with --env-file=.env");
    process.exit(1);
  }

  console.log("🎙  Generating voiceover…");

  const response = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}/with-timestamps`,
    {
      method: "POST",
      headers: {
        "xi-api-key": apiKey,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        text: SCRIPT,
        model_id: "eleven_multilingual_v2",
        voice_settings: {
          stability: 0.5,
          similarity_boost: 0.75,
          style: 0.3,
        },
      }),
    },
  );

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`ElevenLabs API error ${response.status}: ${err}`);
  }

  const data = (await response.json()) as ElevenLabsResponse;

  // Save MP3
  const audioBuffer = Buffer.from(data.audio_base64, "base64");
  writeFileSync(OUTPUT_AUDIO, audioBuffer);
  console.log(`✅  Audio saved → ${OUTPUT_AUDIO}`);

  // Parse words
  const words = parseWords(data.alignment);
  const lastEndFrame =
    Math.round(
      data.alignment.character_end_times_seconds[
        data.alignment.character_end_times_seconds.length - 1
      ] * FPS,
    ) + 20; // small tail padding

  // Write captions-data.ts
  const fileContent = `import { CaptionWord } from "./TACaptions";

// ⚠️  Auto-generated by generate-voiceover.ts — do not edit manually.
// Script: "${SCRIPT}"

export const VOICEOVER_SCRIPT = ${JSON.stringify(SCRIPT)};

export const VOICEOVER_WORDS: CaptionWord[] = ${JSON.stringify(words, null, 2)};

export const VOICEOVER_DURATION_FRAMES = ${lastEndFrame};
`;

  writeFileSync(OUTPUT_DATA, fileContent);
  console.log(`✅  Caption data saved → ${OUTPUT_DATA}`);
  console.log(`📝  ${words.length} words | ${(lastEndFrame / FPS).toFixed(1)}s`);
  console.log("\n🎬  Run 'npm run dev' to preview in Remotion Studio.");
}

generate().catch((err) => {
  console.error("❌ ", err.message);
  process.exit(1);
});
