import { TutorialPart1, TutorialPart2, TutorialPart3, TutorialTemplate, getTutorialDuration, TutorialConfig } from "./TutorialTemplate";

const INTRO_DURATION = 195;  // 6.5s @ 30fps (hook-voiceover.mp3)
const MAIN_DURATION = 1184;  // 39.47s @ 30fps (main-voiceover.mp3)
const OUTRO_DURATION = 76;   // 2.53s @ 30fps (Outro.mp4)

const CONFIG: TutorialConfig = {
  introDuration: INTRO_DURATION,
  mainDuration: MAIN_DURATION,
  outroDuration: OUTRO_DURATION,

  hookAudio: "Tutorial/hook-voiceover.mp3",
  mainAudio: "Tutorial/main-voiceover.mp3",
  screenRecording: "Tutorial/screen-trimmed-muted.mp4",
  introVideo: "Tutorial/Intro.MP4",
  outroVideo: "Tutorial/Outro.mp4",

  screenRecDurationSec: 57.5, // playbackRate ≈ 1.43x

  hookWords: [
    { text: "How do I make", highlight: false },
    { text: "every stop", highlight: true },
    { text: "show up?", highlight: false },
  ],

  introVideoStartFrom: 90, // skip first 3 seconds (zoom-in)

  highlights: [],

  mainWords: [
    { text: "I've", startFrame: 0, endFrame: 7 },
    { text: "already", startFrame: 7, endFrame: 13 },
    { text: "set", startFrame: 13, endFrame: 21 },
    { text: "up", startFrame: 21, endFrame: 24 },
    { text: "5", startFrame: 24, endFrame: 35 },
    { text: "waypoints", startFrame: 35, endFrame: 50 },
    { text: "with", startFrame: 50, endFrame: 56 },
    { text: "real", startFrame: 56, endFrame: 64 },
    { text: "routes", startFrame: 64, endFrame: 74 },
    { text: "enabled,", startFrame: 74, endFrame: 97 },
    { text: "but", startFrame: 97, endFrame: 103 },
    { text: "when", startFrame: 103, endFrame: 107 },
    { text: "you", startFrame: 107, endFrame: 112 },
    { text: "tap", startFrame: 112, endFrame: 118 },
    { text: "Preview,", startFrame: 118, endFrame: 148 },
    { text: "notice", startFrame: 148, endFrame: 154 },
    { text: "the", startFrame: 154, endFrame: 161 },
    { text: "problem.", startFrame: 161, endFrame: 185 },
    { text: "The", startFrame: 185, endFrame: 188 },
    { text: "animation", startFrame: 188, endFrame: 203 },
    { text: "plays,", startFrame: 203, endFrame: 231 },
    { text: "but", startFrame: 231, endFrame: 238 },
    { text: "none", startFrame: 238, endFrame: 244 },
    { text: "of", startFrame: 244, endFrame: 248 },
    { text: "the", startFrame: 248, endFrame: 251 },
    { text: "waypoints", startFrame: 251, endFrame: 266 },
    { text: "show", startFrame: 266, endFrame: 272 },
    { text: "up", startFrame: 272, endFrame: 279 },
    { text: "on", startFrame: 279, endFrame: 283 },
    { text: "screen.", startFrame: 283, endFrame: 311 },
    { text: "To", startFrame: 311, endFrame: 316 },
    { text: "fix", startFrame: 316, endFrame: 322 },
    { text: "this,", startFrame: 322, endFrame: 346 },
    { text: "tap", startFrame: 346, endFrame: 355 },
    { text: "Place", startFrame: 355, endFrame: 369 },
    { text: "Labels.", startFrame: 369, endFrame: 398 },
    { text: "You'll", startFrame: 398, endFrame: 404 },
    { text: "see", startFrame: 404, endFrame: 409 },
    { text: "a", startFrame: 409, endFrame: 412 },
    { text: "row", startFrame: 412, endFrame: 417 },
    { text: "of", startFrame: 417, endFrame: 425 },
    { text: "different", startFrame: 425, endFrame: 431 },
    { text: "pop-up", startFrame: 431, endFrame: 445 },
    { text: "effects.", startFrame: 445, endFrame: 470 },
    { text: "Pick", startFrame: 470, endFrame: 477 },
    { text: "the", startFrame: 477, endFrame: 484 },
    { text: "one", startFrame: 484, endFrame: 488 },
    { text: "you", startFrame: 488, endFrame: 493 },
    { text: "like.", startFrame: 493, endFrame: 520 },
    { text: "I'm", startFrame: 520, endFrame: 535 },
    { text: "going", startFrame: 535, endFrame: 541 },
    { text: "with", startFrame: 541, endFrame: 548 },
    { text: "this", startFrame: 548, endFrame: 553 },
    { text: "style", startFrame: 553, endFrame: 565 },
    { text: "here,", startFrame: 565, endFrame: 588 },
    { text: "and", startFrame: 588, endFrame: 593 },
    { text: "just", startFrame: 593, endFrame: 598 },
    { text: "like", startFrame: 598, endFrame: 606 },
    { text: "that,", startFrame: 606, endFrame: 629 },
    { text: "every", startFrame: 629, endFrame: 637 },
    { text: "single", startFrame: 637, endFrame: 648 },
    { text: "waypoint", startFrame: 648, endFrame: 666 },
    { text: "now", startFrame: 666, endFrame: 672 },
    { text: "pops", startFrame: 672, endFrame: 681 },
    { text: "up", startFrame: 681, endFrame: 691 },
    { text: "as", startFrame: 691, endFrame: 698 },
    { text: "the", startFrame: 698, endFrame: 703 },
    { text: "route", startFrame: 703, endFrame: 710 },
    { text: "animates.", startFrame: 710, endFrame: 751 },
    { text: "You", startFrame: 751, endFrame: 760 },
    { text: "can", startFrame: 760, endFrame: 764 },
    { text: "customize", startFrame: 764, endFrame: 778 },
    { text: "the", startFrame: 778, endFrame: 787 },
    { text: "color,", startFrame: 787, endFrame: 810 },
    { text: "change", startFrame: 810, endFrame: 817 },
    { text: "how", startFrame: 817, endFrame: 824 },
    { text: "the", startFrame: 824, endFrame: 828 },
    { text: "label", startFrame: 828, endFrame: 838 },
    { text: "looks,", startFrame: 838, endFrame: 856 },
    { text: "and", startFrame: 856, endFrame: 865 },
    { text: "adjust", startFrame: 865, endFrame: 872 },
    { text: "the", startFrame: 872, endFrame: 881 },
    { text: "size", startFrame: 881, endFrame: 889 },
    { text: "of", startFrame: 889, endFrame: 893 },
    { text: "the", startFrame: 893, endFrame: 898 },
    { text: "pop-up.", startFrame: 898, endFrame: 925 },
    { text: "Once", startFrame: 925, endFrame: 943 },
    { text: "you're", startFrame: 943, endFrame: 948 },
    { text: "happy,", startFrame: 948, endFrame: 977 },
    { text: "tap", startFrame: 977, endFrame: 982 },
    { text: "the", startFrame: 982, endFrame: 989 },
    { text: "checkmark", startFrame: 989, endFrame: 1001 },
    { text: "and", startFrame: 1001, endFrame: 1008 },
    { text: "export", startFrame: 1008, endFrame: 1018 },
    { text: "in", startFrame: 1018, endFrame: 1024 },
    { text: "HD", startFrame: 1024, endFrame: 1034 },
    { text: "or", startFrame: 1034, endFrame: 1040 },
    { text: "4K.", startFrame: 1040, endFrame: 1070 },
    { text: "That's", startFrame: 1070, endFrame: 1081 },
    { text: "it.", startFrame: 1081, endFrame: 1099 },
    { text: "Every", startFrame: 1099, endFrame: 1106 },
    { text: "waypoint", startFrame: 1106, endFrame: 1119 },
    { text: "showing", startFrame: 1119, endFrame: 1127 },
    { text: "up", startFrame: 1127, endFrame: 1135 },
    { text: "exactly", startFrame: 1135, endFrame: 1154 },
    { text: "as", startFrame: 1154, endFrame: 1160 },
    { text: "it", startFrame: 1160, endFrame: 1163 },
    { text: "should.", startFrame: 1163, endFrame: 1184 },
  ],
};

export const TUTORIAL8_PART1_DURATION = CONFIG.introDuration;
export const TUTORIAL8_PART2_DURATION = CONFIG.mainDuration;
export const TUTORIAL8_PART3_DURATION = CONFIG.outroDuration;
export const TUTORIAL8_DURATION = getTutorialDuration(CONFIG);

export const Tutorial8Part1: React.FC = () => <TutorialPart1 config={CONFIG} />;
export const Tutorial8Part2: React.FC = () => <TutorialPart2 config={CONFIG} />;
export const Tutorial8Part3: React.FC = () => <TutorialPart3 config={CONFIG} />;
export const Tutorial8: React.FC = () => <TutorialTemplate config={CONFIG} />;
